[versions]
jackson = "3.0.4"
lombok = "1.18.42"
annotations = "26.0.2-1"
slf4j = "2.0.17"
junit = "6.0.2"
logback = "1.5.29"
spotless = "8.2.1"

[libraries]
jackson-databind = { module = "tools.jackson.core:jackson-databind", version.ref = "jackson" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
annotations = { module = "org.jetbrains:annotations", version.ref = "annotations" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
